### ISSUE TITLE
DiambraEnv close() hangs

### ISSUE THREAD

**Issue by rssalessio** [diambra/DIAMBRAenvironment#1]
After several tests, together with @alexpalms  we recognized that the diambraGym class is not correctly closing the pipes.

After some investigations, it turns out that the writePipe object can be correctly closed by using the .close() function, whilst the readPipe object hangs in this case.

The reason is that the file opened by readPipe is being kept open by a StreamGobbler object, which uses the readline function to read from that file. The readline function is blocking, thereby we get the aforementioned problem.

There are some solutions: the easiest one to implement is to use a select; another is to use asynchronous I/O.

**Comment by diambra** [comment]
Solved with commit 776e3d86
