### ISSUE TITLE
[FIX] ERROR: Could not find a version that satisfies the requirement dataclasses==0.7 

### ISSUE THREAD

**Issue by sachdevkartik** [diambra/DIAMBRAenvironment#4]
**ERROR**
Faced the following error while installing packages using _pip install -r diambraPipRequirements.txt_

> ERROR: Could not find a version that satisfies the requirement dataclasses==0.7 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
> ERROR: No matching distribution found for dataclasses==0.7
> 

**FIX**
Degrading from python **3.8** to **3.6** worked!

**Comment by diambra** [comment]
Thank you @sachdevkartik for also indicating the FIX for this. Python 3.6 is a requirement for stable_baselines (the version that we used for our tests). Soon we will update the repo so that it will be possible to install everything with a pip command.
